export const SEARCH_CHANGE_VALUE = 'SEARCH_CHANGE_VALUE';

export const SEARCH_LIST_FETCH_START = 'SEARCH_LIST_FETCH_START';
export const SEARCH_LIST_FETCH_SUCCESS = 'SEARCH_LIST_FETCH_SUCCESS';
export const SEARCH_LIST_FETCH_ERROR = 'SEARCH_LIST_FETCH_ERROR';

export const SEARCH_OPTION_SORT_CHANGE = 'SEARCH_OPTION_SORT_CHANGE';
export const SEARCH_LIST_SORT_KEY = 'SEARCH_LIST_SORT_KEY';
